import type { Language } from './types'

const common = {
  benchmark: 'BENCHMARK', signalMix: 'SIGNAL MIX', verification: 'VERIFICATION', readOnlyContext: 'READ-ONLY CONTEXT',
}

const copy: Record<Language, Record<string, string>> = {
  EN: { ...common,
    market: 'MARKET INTELLIGENCE', readOnly: 'READ-ONLY MONITOR', refresh: 'Refresh quotes', refreshing: 'Refreshing', watchPulse: 'WATCHLIST PULSE', portfolioView: 'PORTFOLIO VIEW', signals: 'Signals, without the noise.', positions: 'Positions, at a glance.', watchDesc: 'Heuristic forecasts with live market quotes.', portfolioDesc: 'Saved positions marked to live quotes.', workspace: 'WORKSPACE', switchHelp: 'Switch between signals and positions.', watchlist: 'Watchlist', portfolio: 'Portfolio', priority: 'PRIORITY SIGNALS', top5: 'Top 5 Focus', shortlist: 'Research shortlist', noOrder: 'Not a buy order', rank: 'Rank', symbol: 'Symbol', confidence: 'Confidence', currentMove: 'Current move', forecastTarget: 'Forecast target', livePrice: 'Live price', riskFlag: 'Risk flag', coverage: 'COVERAGE', baseline: 'Baseline', movement: 'Movement', forecast: 'Forecast', status: 'Status', filterBy: 'Filter by', search: 'Search', allForecasts: 'All forecasts', allConfidence: 'All confidence', allStatuses: 'All statuses', high: 'High', medium: 'Medium', low: 'Low', highConfidence: 'High confidence', mediumConfidence: 'Medium confidence', lowConfidence: 'Low confidence', resetFilters: 'Reset filters', onTrack: 'On track', counter: 'Counter', inRange: 'In range', watching: 'Watching', unavailable: 'Unavailable', pending: 'Pending', liveIndependent: 'Forecasts are saved snapshots. Live prices refresh independently from Yahoo Finance.', moveTip: 'Live price movement versus the saved forecast baseline.', targetTip: 'Expected percentage move for the next checkpoint. This is not a price.', riskTip: 'A flag for extension, volatility, liquidity, or data risk. It is not a buy or sell recommendation.', confidenceTip: 'Heuristic conviction. It is not a calibrated probability.', forecastTip: 'UP, FLAT, or DOWN scenario for the next checkpoint. It is not a guarantee.', method: 'How the ranking works', lang: 'Language', source: 'Source', liveQuotes: 'Live quotes', chartHint: 'Click a row to open its chart', closeChart: 'Close chart', filteredCount: 'filtered', rowsPerPage: 'Rows per page', previous: 'Previous', next: 'Next', page: 'Page', pageOf: 'of', pageSuffix: '', pagination: 'Pagination',
  },
  ID: { ...common,
    market: 'INTELIJEN PASAR', readOnly: 'MONITOR BACA SAJA', refresh: 'Segarkan harga', refreshing: 'Menyegarkan', watchPulse: 'PANTAUAN WATCHLIST', portfolioView: 'TAMPILAN PORTOFOLIO', signals: 'Sinyal yang mudah dibaca.', positions: 'Posisi dalam satu tampilan.', watchDesc: 'Forecast heuristik dengan harga pasar live.', portfolioDesc: 'Posisi tersimpan berdasarkan harga live.', workspace: 'RUANG KERJA', switchHelp: 'Pilih sinyal atau posisi.', watchlist: 'Watchlist', portfolio: 'Portofolio', priority: 'SINYAL PRIORITAS', top5: '5 Fokus Utama', shortlist: 'Daftar riset', noOrder: 'Bukan perintah beli', rank: 'Peringkat', symbol: 'Kode', confidence: 'Keyakinan', currentMove: 'Pergerakan kini', forecastTarget: 'Target forecast', livePrice: 'Harga live', riskFlag: 'Tanda risiko', coverage: 'CAKUPAN', baseline: 'Baseline', movement: 'Pergerakan', forecast: 'Forecast', status: 'Status', filterBy: 'Filter berdasarkan', search: 'Cari', allForecasts: 'Semua forecast', allConfidence: 'Semua keyakinan', allStatuses: 'Semua status', high: 'Tinggi', medium: 'Sedang', low: 'Rendah', highConfidence: 'Keyakinan tinggi', mediumConfidence: 'Keyakinan sedang', lowConfidence: 'Keyakinan rendah', resetFilters: 'Reset filter', onTrack: 'Sesuai arah', counter: 'Berlawanan', inRange: 'Dalam rentang', watching: 'Pantau', unavailable: 'Tidak tersedia', pending: 'Menunggu', benchmark: 'BENCHMARK', signalMix: 'KOMPOSISI SINYAL', verification: 'VERIFIKASI', readOnlyContext: 'KONTEKS BACA SAJA', liveIndependent: 'Forecast tersimpan. Harga live diperbarui terpisah dari Yahoo Finance.', moveTip: 'Pergerakan harga live dibandingkan baseline forecast tersimpan.', targetTip: 'Perkiraan persentase gerak sampai checkpoint berikutnya. Ini bukan harga.', riskTip: 'Tanda risiko dari kenaikan berlebih, volatilitas, likuiditas, atau kualitas data. Bukan rekomendasi beli atau jual.', confidenceTip: 'Keyakinan heuristik. Bukan probabilitas terkalibrasi.', forecastTip: 'Skenario UP, FLAT, atau DOWN untuk checkpoint berikutnya. Bukan jaminan.', method: 'Cara peringkat bekerja', lang: 'Bahasa', source: 'Sumber', liveQuotes: 'Harga live', chartHint: 'Klik baris untuk membuka grafik', closeChart: 'Tutup grafik', filteredCount: 'tersaring', rowsPerPage: 'Baris per halaman', previous: 'Sebelumnya', next: 'Berikutnya', page: 'Halaman', pageOf: 'dari', pageSuffix: '', pagination: 'Paginasi',
  },
  MY: { ...common,
    market: 'INTELIJEN PASAR', readOnly: 'PEMANTAU BACA SAHAJA', refresh: 'Segar harga', refreshing: 'Sedang segar', watchPulse: 'PANTAUAN WATCHLIST', portfolioView: 'PAPARAN PORTFOLIO', signals: 'Isyarat yang mudah dibaca.', positions: 'Posisi dalam satu paparan.', watchDesc: 'Ramalan heuristik dengan harga pasaran live.', portfolioDesc: 'Posisi tersimpan berdasarkan harga live.', workspace: 'RUANG KERJA', switchHelp: 'Pilih isyarat atau posisi.', watchlist: 'Watchlist', portfolio: 'Portfolio', priority: 'ISYARAT KEUTAMAAN', top5: '5 Fokus Utama', shortlist: 'Senarai kajian', noOrder: 'Bukan arahan beli', rank: 'Kedudukan', symbol: 'Kod', confidence: 'Keyakinan', currentMove: 'Pergerakan kini', forecastTarget: 'Sasaran ramalan', livePrice: 'Harga live', riskFlag: 'Tanda risiko', coverage: 'LIPUTAN', baseline: 'Baseline', movement: 'Pergerakan', forecast: 'Ramalan', status: 'Status', filterBy: 'Tapis mengikut', search: 'Cari', allForecasts: 'Semua ramalan', allConfidence: 'Semua keyakinan', allStatuses: 'Semua status', high: 'Tinggi', medium: 'Sederhana', low: 'Rendah', highConfidence: 'Keyakinan tinggi', mediumConfidence: 'Keyakinan sederhana', lowConfidence: 'Keyakinan rendah', resetFilters: 'Tetap semula penapis', onTrack: 'Mengikut arah', counter: 'Berlawanan', inRange: 'Dalam julat', watching: 'Pantau', unavailable: 'Tidak tersedia', pending: 'Menunggu', benchmark: 'PENANDA ARAS', signalMix: 'CAMPURAN ISYARAT', verification: 'PENGESAHAN', readOnlyContext: 'KONTEKS BACA SAHAJA', liveIndependent: 'Ramalan disimpan. Harga live dikemas kini secara berasingan daripada Yahoo Finance.', moveTip: 'Pergerakan harga live berbanding baseline ramalan yang disimpan.', targetTip: 'Anggaran pergerakan peratus untuk checkpoint seterusnya. Ini bukan harga.', riskTip: 'Tanda risiko untuk kenaikan berlebihan, turun naik, kecairan, atau kualiti data. Bukan cadangan beli atau jual.', confidenceTip: 'Keyakinan heuristik. Bukan kebarangkalian yang ditentukur.', forecastTip: 'Senario UP, FLAT, atau DOWN untuk checkpoint seterusnya. Bukan jaminan.', method: 'Cara kedudukan dikira', lang: 'Bahasa', source: 'Sumber', liveQuotes: 'Harga live', chartHint: 'Klik baris untuk membuka graf', closeChart: 'Tutup graf', filteredCount: 'ditapis', rowsPerPage: 'Baris setiap halaman', previous: 'Sebelumnya', next: 'Seterusnya', page: 'Halaman', pageOf: 'daripada', pageSuffix: '', pagination: 'Paginasi',
  },
  CN: { ...common,
    market: '市场情报', readOnly: '只读监控', refresh: '刷新价格', refreshing: '正在刷新', watchPulse: '自选股动态', portfolioView: '投资组合', signals: '清晰的信号。', positions: '一目了然的持仓。', watchDesc: '启发式预测与实时市场价格。', portfolioDesc: '按实时价格计算的持仓。', workspace: '工作区', switchHelp: '切换信号或持仓。', watchlist: '自选股', portfolio: '投资组合', priority: '优先信号', top5: '重点关注 5 只', shortlist: '研究清单', noOrder: '不是买入指令', rank: '排名', symbol: '代码', confidence: '信心', currentMove: '当前变动', forecastTarget: '预测目标', livePrice: '实时价格', riskFlag: '风险提示', coverage: '覆盖范围', baseline: '基准价', movement: '变动', forecast: '预测', status: '状态', filterBy: '筛选条件', search: '搜索', allForecasts: '全部预测', allConfidence: '全部信心', allStatuses: '全部状态', high: '高', medium: '中', low: '低', highConfidence: '高信心', mediumConfidence: '中信心', lowConfidence: '低信心', resetFilters: '重置筛选', onTrack: '方向一致', counter: '方向相反', inRange: '范围内', watching: '观察中', unavailable: '不可用', pending: '等待中', benchmark: '基准', signalMix: '信号分布', verification: '验证', readOnlyContext: '只读信息', liveIndependent: '预测是保存的快照。实时价格独立来自 Yahoo Finance。', moveTip: '实时价格相对于保存的预测基准价的变动。', targetTip: '到下一个检查点的预期百分比变动。不是价格。', riskTip: '提示涨幅过大、波动、流动性或数据风险。不是买卖建议。', confidenceTip: '启发式信心。不是校准概率。', forecastTip: '下一个检查点的 UP、FLAT 或 DOWN 情景。不是保证。', method: '排名方式', lang: '语言', source: '来源', liveQuotes: '实时价格', chartHint: '点击行打开图表', closeChart: '关闭图表', filteredCount: '个结果', rowsPerPage: '每页行数', previous: '上一页', next: '下一页', page: '第', pageOf: '页，共', pageSuffix: '页', pagination: '分页',
  },
}

export const tr = (language: Language, key: string) => copy[language][key] || copy.EN[key] || key
export function localizedStatus(language: Language, label: string) {
  const keys: Record<string, string> = { 'On track': 'onTrack', Counter: 'counter', 'In range': 'inRange', Watching: 'watching', Unavailable: 'unavailable', Pending: 'pending' }
  return tr(language, keys[label] || label)
}
